version: "3.2"

services:
  dgraph-zero:
    container_name: d-zero
    image: dgraph/dgraph:latest
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=dgraph-zero:5080
  dgraph-alpha:
    container_name: d-alpha
    image: dgraph/dgraph:latest
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=dgraph-alpha:7080 --zero=dgraph-zero:5080 --security whitelist=172.17.0.0:172.21.0.1,192.168.0.0/16;
  dgraph-ratel:
    container_name: d-ratel
    image: dgraph/ratel:latest
    ports:
      - 8000:8000
    command: dgraph-ratel
